name: Java Jar

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      LANG: en_US.UTF-8
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [19]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # java: [8, 11, 17, 18, 19]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs