name: Java Jar

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      LANG: en_US.UTF-8
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [17]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # java: [8, 11, 17, 21]

    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Checkout Core
        run: |
          git clone --branch develop --depth=1 https://github.com/MarcelloPerathoner/josm.git core
          cd core
          echo "JOSM_DIR=$(pwd)" >> $GITHUB_ENV
          scripts/main_josm_version_github.py MarcelloPerathoner/josm >> $GITHUB_ENV

      - name: Generate release tag
        id: tag
        run: |
          cd core
          echo "RELEASE_TAG=${{ env.MAIN_JOSM_VERSION }}-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Build Core
        run: |
          cd core
          ./gradlew jar sourcesJar javadocJar

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            core/build/libs/*.jar
